import {describe,it,expect,vi,afterEach} from 'vitest';
import {newProject,newItem} from '@/lib/defaults';
import {useStudio} from '@/lib/store';
import {generateWorktops} from '@/lib/worktops';
import {canPlace,findFreePlacement,validate,isItemOnWall} from '@/lib/geometry';
import {serviceEntries,elevationDimensions} from '@/lib/drawingPack';
import {bufferedProjectStorage,flushProjectStorage,getLocalSaveStatus} from '@/lib/saveStatus';
import {exportPdf} from '@/lib/pdf';
function room(){const p=newProject('Acceptance fixes');p.rules={wallClearance:0,componentGap:0,snap:25};p.items=[];return p}
function setup(){const p=room();p.items=[{...newItem('Base cabinet'),x:500,z:500}];useStudio.getState().endEdit();useStudio.setState({projects:[p],activeId:p.id,past:[],future:[],view:'top',selectedId:p.items[0].id});return p}
afterEach(()=>{flushProjectStorage();vi.useRealTimers();vi.unstubAllGlobals()});
describe('acceptance failures',()=>{
 it('undoes field resizing and single movement without changing the current view',()=>{const p=setup(),id=p.items[0].id;useStudio.getState().updateItem(id,{width:725});useStudio.getState().setView('3d');useStudio.getState().undo();expect(useStudio.getState().projects[0].items[0].width).toBe(600);expect(useStudio.getState().view).toBe('3d');useStudio.getState().moveItem(id,{x:1000});useStudio.getState().undo();expect(useStudio.getState().projects[0].items[0].x).toBe(500)});
 it('undoes a completed drag in one step and leaves unrelated projects shared',()=>{const p=setup(),other=room();useStudio.setState({projects:[p,other]});const s=useStudio.getState();s.checkpoint();s.moveItem(p.items[0].id,{x:700});s.moveItem(p.items[0].id,{x:900});s.endEdit();expect(useStudio.getState().past).toHaveLength(1);expect(useStudio.getState().past[0].projects[1]).toBe(other);s.undo();expect(useStudio.getState().projects[0].items[0].x).toBe(500);s.redo();expect(useStudio.getState().projects[0].items[0].x).toBe(900)});
 it('rejects unsupported room dimensions without committing history',()=>{setup();useStudio.getState().updateProject({roomWidth:999999});expect(useStudio.getState().projects[0].roomWidth).not.toBe(999999);expect(useStudio.getState().past).toHaveLength(0);expect(useStudio.getState().editError).toContain('dimensions')});
 it('bridges a lower integrated dishwasher with the neighbouring cabinet worktop',()=>{const p=room();const a={...newItem('Base cabinet'),x:0,z:0,depth:600},b={...newItem('Dishwasher'),x:600,z:0},c={...newItem('Sink base'),x:1200,z:0,width:600};p.items=[a,b,c];const tops=generateWorktops(p);expect(tops).toHaveLength(1);expect(tops[0]).toMatchObject({y:870,width:1800});expect(p.items[1].height).toBe(820)});
 it('puts taps on the sink, not the first empty floor grid cell',()=>{const p=room();const sink={...newItem('Sink base'),x:1200,z:0};p.items=[sink,...generateWorktops({...p,items:[sink]})];const tap=findFreePlacement(p,newItem('Tap'));expect(tap.x).toBeGreaterThan(sink.x);expect(tap.x+tap.width).toBeLessThan(sink.x+sink.width);expect(tap.y).toBe(908);expect(canPlace(p,tap)).toBe(true)});
 it('places a base-unit copy flush beside its source at the same depth',()=>{const p=room();p.rules.componentGap=2;const a={...newItem('Base cabinet'),x:1000,z:700};p.items=[a];const q=findFreePlacement(p,{...a,id:'copy',x:1050});expect(q.x).toBe(1602);expect(q.z).toBe(700)});
 it('keeps a copied wall cabinet against its assigned wall',()=>{const p=room();const source={...newItem('Wall cabinet'),x:200,z:0,wallSide:'back' as const};p.items=[source];const q=findFreePlacement(p,{...source,id:'copy',x:source.x+50});expect(q.z).toBe(0);expect(q.wallSide).toBe('back');expect(canPlace(p,q)).toBe(true)});
 it('rejects a backsplash behind a tall cabinet instead of selecting an unrelated wall',()=>{const p=room();p.items=[{...newItem('Tall cabinet'),x:0,z:0,width:1800},{...newItem('Worktop'),x:0,z:0,width:1800,y:870,height:38}];const splash=findFreePlacement(p,newItem('Backsplash'));expect(canPlace(p,splash)).toBe(false)});
 it('places openings at a wall and ignores hidden geometry in placement',()=>{const p=room();p.items=[{...newItem('Wall segment'),x:0,z:0,width:p.roomWidth,depth:p.roomDepth,height:p.roomHeight,visible:false}];const door=findFreePlacement(p,newItem('Door opening'));expect(door.z).toBe(0);expect(canPlace(p,door)).toBe(true);expect(validate(p)).toEqual([])});
 it('reports insufficient island circulation even where objects do not overlap',()=>{const p=room();p.roomWidth=6000;p.roomDepth=6000;p.items=[{...newItem('Sink base'),x:1000,z:0},{...newItem('Kitchen island'),x:1000,z:700}];expect(validate(p).some(s=>s.includes('circulation'))).toBe(true)});
 it('does not put a unit on an elevation using a stale wall tag',()=>{const p=room();const i={...newItem('Base cabinet'),x:1000,z:1000,wallSide:'front' as const};expect(isItemOnWall(p,i,'front')).toBe(false)});
 it('keeps full cabinet height in elevation chains despite a lower appliance',()=>{const p=room();p.items=[{...newItem('Base cabinet'),x:0,z:0},{...newItem('Dishwasher'),x:600,z:0},{...newItem('Sink base'),x:1200,z:0},{...newItem('Filler panel'),x:2000,z:0,width:100}];const d=elevationDimensions(p,'back',p.items);expect(d.heights).toContain(p.roomHeight-870);expect(d.heights).not.toContain(p.roomHeight-820);expect(d.widths).toContain(2100)});
 it('lists built-in services and retains host references in the real PDF',()=>{const p=room();p.items=[newItem('Hob base'),newItem('Sink base'),newItem('Oven tower'),newItem('Fridge housing'),{...newItem('Kitchen island'),islandAppliance:'sink'}];expect(serviceEntries(p).map(e=>e.kind)).toEqual(['Integrated hob','Integrated sink','Integrated oven','Integrated fridge','Island sink','Island tap']);const data=exportPdf(p,false).output();expect(data).toContain('Integrated hob');expect(data).toContain('Integrated oven');expect(data).toContain('Integrated in')});
});
describe('buffered local saving',()=>{
 it('coalesces edits and skips serializing selection-only updates, then flushes before leaving',()=>{vi.useFakeTimers();const storage={getItem:vi.fn(()=>null),setItem:vi.fn(),removeItem:vi.fn()};vi.stubGlobal('window',{localStorage:storage});const save=bufferedProjectStorage(),projects=[room()],state={projects,activeId:'a',view:'top'};save.setItem('a',{state,version:0});for(let n=0;n<100;n++)save.setItem('a',{state:{...state,selectedId:String(n)},version:0});expect(storage.setItem).not.toHaveBeenCalled();expect(getLocalSaveStatus()).toBe('pending');flushProjectStorage();expect(storage.setItem).toHaveBeenCalledTimes(1);expect(JSON.parse(storage.setItem.mock.calls[0][1]).state.projects).toHaveLength(1);expect(getLocalSaveStatus()).toBe('saved')});
});
