import {describe,it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {referenceDepth,calibratedWidth,validDrawingReference} from '../lib/drawingReference';
import {parseCadPlan,cadPlanView} from '../lib/cadPlan';
const document=(entities:string,header='')=>`0\nSECTION\n2\nHEADER\n${header}0\nENDSEC\n0\nSECTION\n2\nENTITIES\n${entities}0\nENDSEC\n0\nEOF\n`;
describe('native DXF plan loading',()=>{
 it('keeps exact CAD scale when the reference is rasterised to whole pixels',()=>{const r={name:'CAD',dataUrl:'data:image/webp;base64,AAAA',pixelWidth:2048,pixelHeight:1658,aspectRatio:4200/3400,widthMm:4200,x:0,z:0,opacity:.45,visible:true};expect(referenceDepth(r)).toBeCloseTo(3400,9);expect(calibratedWidth({x:0,y:0},{x:0,y:1},3400,r.pixelWidth,r.pixelHeight,r.aspectRatio)).toBeCloseTo(4200,9);expect(validDrawingReference(JSON.parse(JSON.stringify(r)))).toBe(true);expect(validDrawingReference({...r,aspectRatio:-1})).toBe(false);});
 it('preserves millimetres and lets the user choose meaningful layers',()=>{const p=parseCadPlan(readFileSync('public/examples/kitchen-plan.dxf','utf8'));expect(p.unit).toBe('mm');expect(p.layers).toEqual(['BASE UNITS','ISLAND','ROOM']);expect(cadPlanView(p,['ROOM'],'mm')).toMatchObject({widthMm:4200,depthMm:3400});expect(cadPlanView(p,['ISLAND'],'mm')).toMatchObject({widthMm:1800,depthMm:800});expect(p.strokes[0].points[0]).toEqual(p.strokes[0].points.at(-1))});
 it('converts an imperial plan without fitting it to an arbitrary room',()=>{const p=parseCadPlan(document('0\nLINE\n8\nWALL\n10\n-10\n20\n-10\n11\n110\n21\n70\n','9\n$INSUNITS\n70\n1\n'));expect(p.unit).toBe('in');expect(cadPlanView(p,p.layers,'in')).toMatchObject({widthMm:3048,depthMm:2032})});
 it('samples bulged polyline segments instead of replacing arcs with chords',()=>{const p=parseCadPlan(document('0\nLWPOLYLINE\n8\nCURVE\n90\n2\n70\n0\n10\n0\n20\n0\n42\n1\n10\n1000\n20\n0\n'));expect(p.strokes[0].points.length).toBeGreaterThan(20);const bounds=cadPlanView(p,p.layers,'mm');expect(bounds.widthMm).toBeCloseTo(1000);expect(bounds.depthMm).toBeCloseTo(500)});
 it('rotates and scales inserted blocks around their source origin',()=>{const s='0\nSECTION\n2\nBLOCKS\n0\nBLOCK\n2\nCAB\n10\n100\n20\n100\n0\nLINE\n8\n0\n10\n100\n20\n100\n11\n300\n21\n200\n0\nENDBLK\n0\nENDSEC\n0\nSECTION\n2\nENTITIES\n0\nINSERT\n8\nCABINET\n2\nCAB\n10\n1000\n20\n2000\n41\n2\n42\n3\n50\n90\n0\nENDSEC\n0\nEOF\n';const p=parseCadPlan(s);expect(p.strokes[0].layer).toBe('CABINET');expect(p.strokes[0].points[0].x).toBeCloseTo(1000);expect(p.strokes[0].points[0].y).toBeCloseTo(2000);expect(p.strokes[0].points[1].x).toBeCloseTo(700);expect(p.strokes[0].points[1].y).toBeCloseTo(2400)});
 it('reports omitted annotations, unspecified units and invalid input',()=>{const p=parseCadPlan(document('0\nTEXT\n1\nIGNORE\n10\n0\n20\n0\n40\n20\n0\nLINE\n10\n0\n20\n0\n11\n1000\n21\n1000\n'));expect(p.unit).toBe('unknown');expect(p.ignored).toBe(1);expect(()=>cadPlanView(p,[],'mm')).toThrow('Select');expect(()=>parseCadPlan('AutoCAD Binary DXF')).toThrow('ASCII');expect(()=>cadPlanView(p,p.layers,'m')).toThrow('units')});
});
