import {describe,it,expect,beforeEach} from 'vitest';
import {newItem,newProject} from '@/lib/defaults';
import {islandWorktops,kitchenProject,kitchenSpecification,ISLAND_STYLES} from '@/lib/kitchenConfig';
import {worktopCutouts} from '@/lib/renderGeometry';
import {canPlace,validate,footprint} from '@/lib/geometry';
import {generateWorktops} from '@/lib/worktops';
import {useStudio} from '@/lib/store';
import {isProjectBackup} from '@/lib/backup';
import {exportPdf} from '@/lib/pdf';
import {JoineryItem} from '@/types/model';
function kitchen(){const p=newProject('Customer kitchen');p.roomWidth=6000;p.roomDepth=5000;p.items=[{...newItem('Kitchen island'),x:1800,z:1800,width:1800,height:920,depth:900}];return p}
describe('customer island configurations share their exact worktop geometry',()=>{
 it.each(ISLAND_STYLES)('has valid %s counters in every orientation',islandStyle=>{for(const rotation of [0,90,180,270]){const p=kitchen();p.items[0]={...p.items[0],islandStyle,rotation};const q=kitchenProject(p);expect(validate(q)).toEqual([]);expect(q.items.filter(i=>i.type==='Worktop')).toHaveLength(islandStyle==='dining'?2:1);expect(kitchenProject(q).items).toHaveLength(q.items.length);expect(generateWorktops(p).filter(i=>i.type==='Worktop')).toEqual(islandWorktops(p.items[0]));}});
 it('extends the breakfast counter behind the carcass and keeps its finished height',()=>{const i={...kitchen().items[0],islandStyle:'breakfast' as const,topThickness:20,topOverhang:30,seatingOverhang:350};const [t]=islandWorktops(i);expect(t.x).toBe(i.x-30);expect(t.z).toBe(i.z-350);expect(t.width).toBe(1860);expect(t.depth).toBe(1280);expect(t.y+t.height).toBe(i.y+i.height)});
 it('places the lower dining extension beside the slab, with matching edges',()=>{const i={...kitchen().items[0],islandStyle:'dining' as const,counterExtension:1100};const [main,dining]=islandWorktops(i);expect(dining.x).toBe(main.x+main.width);expect(dining.z).toBe(main.z);expect(dining.y+dining.height).toBe(740);expect(dining.width).toBe(1100)});
 it.each(['sink','hob','grill'] as const)('keeps %s cutouts over the cabinet after extension and rotation',islandAppliance=>{for(const rotation of [0,90,180,270]){const i={...kitchen().items[0],islandStyle:'extended' as const,counterExtension:1100,islandAppliance,rotation};const [top]=islandWorktops(i),[hole]=worktopCutouts(top,[i]);expect(hole).toBeDefined();const a=rotation*Math.PI/180,tf=footprint(top),sf=footprint(i),offset=islandAppliance==='sink'?i.depth*.03:15;expect(top.x+tf.width/2+(hole.x*Math.cos(a)+hole.z*Math.sin(a))*1000).toBeCloseTo(i.x+sf.width/2+Math.sin(a)*offset);expect(top.z+tf.depth/2+(-hole.x*Math.sin(a)+hole.z*Math.cos(a))*1000).toBeCloseTo(i.z+sf.depth/2+Math.cos(a)*offset);}});
 it('rejects overhangs outside the room even when the carcass fits',()=>{const p=kitchen(),i={...p.items[0],x:20,islandStyle:'breakfast' as const};expect(canPlace(p,i,i.id)).toBe(false);expect(validate({...p,items:[i]}).some(s=>s.includes('worktop'))).toBe(true)});
 it('does not generate cutouts for storage-only or hidden islands',()=>{const i=kitchen().items[0];expect(worktopCutouts(islandWorktops(i)[0],[i])).toEqual([]);expect(islandWorktops({...i,visible:false})).toEqual([])});
});
describe('customer specifications survive editing, recovery and drawing export',()=>{
 beforeEach(()=>{const p=kitchen();useStudio.setState({projects:[p],activeId:p.id,past:[],future:[],editError:''})});
 it('undoes and restores all kitchen selections together, including generated tops',()=>{const p=useStudio.getState().projects[0],i=p.items[0];const specification:Partial<JoineryItem>={frontStyle:'slim-shaker',handleFinish:'Brass',handleLength:192,hardware:'Cup pull',plinthStyle:'legs',plinthHeight:140,islandStyle:'hob',hobStyle:'gas',hobZones:5,topThickness:20};useStudio.getState().updateItem(i.id,specification);let q=useStudio.getState().projects[0];expect(q.items[0]).toMatchObject(specification);expect(kitchenProject(q).items[1].height).toBe(20);expect(isProjectBackup(JSON.parse(JSON.stringify([q])) )).toBe(true);useStudio.getState().undo();expect(useStudio.getState().projects[0].items[0].islandStyle).toBeUndefined();useStudio.getState().redo();q=useStudio.getState().projects[0];expect(q.items[0]).toMatchObject(specification);expect(kitchenSpecification(q.items[0])).toContain('Brass');expect(exportPdf(q,false).getNumberOfPages()).toBe(9)});
 it('moves and updates a linked top atomically, and removes it with its island',()=>{const p=useStudio.getState().projects[0],i=p.items[0];p.items.push(...islandWorktops(i));useStudio.setState({projects:[p]});useStudio.getState().updateItem(i.id,{x:i.x+200,topThickness:25});let q=useStudio.getState().projects[0];expect(q.items[1].x).toBe(i.x+170);expect(q.items[1].height).toBe(25);useStudio.getState().deleteItem(i.id);expect(useStudio.getState().projects[0].items).toEqual([]);useStudio.getState().undo();expect(useStudio.getState().projects[0].items).toHaveLength(2)});
 it('rejects an invalid extension without changing the saved design or undo history',()=>{const p=useStudio.getState().projects[0];useStudio.getState().updateItem(p.items[0].id,{x:4000});const before=JSON.stringify(useStudio.getState().projects);const history=useStudio.getState().past.length;useStudio.getState().updateItem(p.items[0].id,{islandStyle:'extended',counterExtension:1800});expect(JSON.stringify(useStudio.getState().projects)).toBe(before);expect(useStudio.getState().past).toHaveLength(history);expect(useStudio.getState().editError).toContain('counter configuration')});
 it('rejects malformed configuration in imported backups',()=>{const p=kitchen();for(const patch of [{hobZones:3},{islandStyle:'bogus'},{topThickness:-1},{handleFinish:'bogus'}])expect(isProjectBackup([{...p,items:[{...p.items[0],...patch}]}])).toBe(false)});
});
