import {describe,it,expect} from 'vitest';
import {newProject,newItem} from '@/lib/defaults';
import {assertSceneResourcesReady,getSceneResources,modelResourceId,retainSceneResource,sceneResourceState,setSceneResourceStatus} from '@/lib/sceneResources';
const resource=(id:string,kind:'model'|'texture'|'environment'='model')=>({id,kind,url:'/test-resource',label:'Test '+kind});
describe('customer render resource recovery',()=>{
 it('blocks final export until required models have finished and reports an actual download failure',()=>{const p={...newProject(),items:[{...newItem('Hob base'),hobStyle:'gas' as const,hobZones:4 as const}]},r=resource(modelResourceId('gas-hob')),release=retainSceneResource(r);try{expect(()=>assertSceneResourcesReady(p)).toThrow('still loading');setSceneResourceStatus(r,'error');expect(()=>assertSceneResourcesReady(p)).toThrow('Retry loading');setSceneResourceStatus(r,'ready');expect(()=>assertSceneResourcesReady(p)).not.toThrow()}finally{release()}});
 it('does not block a different design on an unused failed model',()=>{const r=resource(modelResourceId('ceramic-mug')),release=retainSceneResource(r);try{setSceneResourceStatus(r,'error');expect(sceneResourceState({...newProject(),items:[]})).toEqual({failed:[],loading:0})}finally{release()}});
 it('retains a shared texture failure until the last visible surface releases it and allows a fresh retry',()=>{const p={...newProject(),items:[]},r=resource('texture:shared','texture'),a=retainSceneResource(r),b=retainSceneResource(r);setSceneResourceStatus(r,'error');a();expect(()=>assertSceneResourcesReady(p)).toThrow('could not load');b();expect(()=>assertSceneResourcesReady(p)).not.toThrow();const retry=retainSceneResource(r);try{expect(sceneResourceState(p).loading).toBe(1);setSceneResourceStatus(r,'ready');expect(()=>assertSceneResourcesReady(p)).not.toThrow()}finally{retry()}});
 it('gates lighting and does not retain resources after leaving the 3D view',()=>{const p={...newProject(),items:[]},r=resource('environment:test','environment'),release=retainSceneResource(r);try{expect(()=>assertSceneResourcesReady(p)).toThrow('still loading');setSceneResourceStatus(r,'error');expect(()=>assertSceneResourcesReady(p)).toThrow('Test environment')}finally{release()}expect(getSceneResources()).toEqual([])});
});
