import {describe,it,expect,beforeAll} from 'vitest';
import * as THREE from 'three';
import {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader.js';
import {unzipSync} from 'fflate';
import {readFileSync} from 'node:fs';
import {exportSceneGlb,exportRenderPackage} from '@/lib/sceneExport';
import {newProject} from '@/lib/defaults';
import {createExportCanvas,imageCanvas,installNodeGraphics} from '../scripts/render/node-graphics';
const json=(b:ArrayBuffer)=>JSON.parse(new TextDecoder().decode(new Uint8Array(b,20,new DataView(b).getUint32(12,true))));
beforeAll(()=>installNodeGraphics());
describe('actual customer scene export',()=>{
 it('retains world-space dimensions and camera while excluding hidden geometry and editor tools',async()=>{const parent=new THREE.Group();parent.position.set(1,0,2);const model=new THREE.Group();model.position.x=.5;parent.add(model);const cabinet=new THREE.Mesh(new THREE.BoxGeometry(1,1,.6),new THREE.MeshStandardMaterial());cabinet.position.y=.5;model.add(cabinet);const tool=new THREE.Mesh(new THREE.BoxGeometry(100,100,100),new THREE.MeshBasicMaterial());tool.userData.editorOnly=true;model.add(tool);const hidden=tool.clone();hidden.userData={};hidden.visible=false;model.add(hidden);const cameraParent=new THREE.Group();cameraParent.position.set(2,0,-1);const camera=new THREE.PerspectiveCamera(60,1.5,.01,100);camera.position.set(1,1,3);cameraParent.add(camera);camera.lookAt(new THREE.Vector3(1.5,.5,2));const bytes=await exportSceneGlb(model,camera),gltf=await new GLTFLoader().parseAsync(bytes,'');const bounds=new THREE.Box3().setFromObject(gltf.scene);expect(bounds.min.toArray()).toEqual(expect.arrayContaining([1,0]));expect(bounds.max.x).toBeCloseTo(2);expect(bounds.max.y).toBeCloseTo(1);expect(bounds.min.z).toBeCloseTo(1.7);expect(bounds.max.z).toBeCloseTo(2.3);expect(gltf.cameras).toHaveLength(1);expect(gltf.cameras[0].getWorldPosition(new THREE.Vector3()).toArray()).toEqual([3,1,2]);expect(model.children).toHaveLength(3);expect(tool.parent).toBe(model);expect(camera.parent).toBe(cameraParent)});
 it('embeds texture pixels, physical finishes and texture scale in the real glTF binary',async()=>{const canvas=createExportCanvas(2,2),ctx=canvas.getContext('2d');ctx.fillStyle='#c2a173';ctx.fillRect(0,0,2,2);const map=new THREE.CanvasTexture(canvas as unknown as HTMLCanvasElement);map.colorSpace=THREE.SRGBColorSpace;map.repeat.set(2,3);const material=new THREE.MeshPhysicalMaterial({map,roughness:.35,metalness:.08,clearcoat:.4});const model=new THREE.Mesh(new THREE.BoxGeometry(1,1,1),material),bytes=await exportSceneGlb(model,new THREE.PerspectiveCamera()),gltf=json(bytes);expect(gltf.images).toHaveLength(1);expect(gltf.images[0].bufferView).toBeTypeOf('number');const finish=gltf.materials[0];expect(finish.pbrMetallicRoughness.roughnessFactor).toBe(.35);expect(finish.extensions.KHR_materials_clearcoat.clearcoatFactor).toBe(.4);expect(finish.pbrMetallicRoughness.baseColorTexture.extensions.KHR_texture_transform.scale).toEqual([2,3]);expect(gltf.bufferViews[gltf.images[0].bufferView].byteLength).toBeGreaterThan(50);const view=gltf.bufferViews[gltf.images[0].bufferView],start=20+new DataView(bytes).getUint32(12,true)+8+(view.byteOffset??0),image=await imageCanvas(Buffer.from(bytes.slice(start,start+view.byteLength)));expect(Array.from(image.getContext('2d').getImageData(0,0,1,1).data)).toEqual([194,161,115,255])});
 it('produces a portable render package with matching dimensions, selected quality and executable launcher',async()=>{const project=newProject(),model=new THREE.Mesh(new THREE.BoxGeometry(1,1,1),new THREE.MeshStandardMaterial()),camera=new THREE.PerspectiveCamera();const bytes=await exportRenderPackage({project,model,camera,aspect:1.5,quality:'customer',readAsset:async url=>new Uint8Array(readFileSync('public'+url))});const files=unzipSync(bytes),settings=JSON.parse(new TextDecoder().decode(files['settings.json']));expect(Object.keys(files).sort()).toEqual(['README.txt','environment.hdr','render.py','run-render.bat','run-render.command','scene.glb','settings.json']);expect(settings).toMatchObject({quality:'customer',room:{width:project.roomWidth/1000,height:project.roomHeight/1000,depth:project.roomDepth/1000}});expect(new DataView(files['scene.glb'].buffer).getUint32(0,true)).toBe(0x46546c67);let offset=new DataView(bytes.buffer,bytes.byteOffset).getUint32(bytes.length-6,true),mode=0;while(offset<bytes.length-46){const d=new DataView(bytes.buffer,bytes.byteOffset+offset);if(d.getUint32(0,true)===0x02014b50){const name=new TextDecoder().decode(bytes.slice(offset+46,offset+46+d.getUint16(28,true)));if(name==='run-render.command')mode=d.getUint32(38,true)>>>16;offset+=46+d.getUint16(28,true)+d.getUint16(30,true)+d.getUint16(32,true);}else break;}expect(mode&0o111).toBe(0o111)},15000);
});
