import {afterEach,beforeEach,describe,it,expect,vi} from 'vitest';
import {newItem,newProject} from '@/lib/defaults';
import {useStudio} from '@/lib/store';
import {canPlace,validate} from '@/lib/geometry';
function setup(){const p=newProject('Reliability');p.roomWidth=2000;p.roomHeight=2400;p.roomDepth=2000;p.rules={wallClearance:0,componentGap:0,snap:25,serviceClearance:50};p.items=[{...newItem('Base cabinet'),x:0,z:0,width:400,depth:400,groupId:'g'},{...newItem('Base cabinet'),x:1500,z:0,width:400,depth:400,groupId:'g'}];useStudio.setState({projects:[p],activeId:p.id,past:[],future:[],editError:''});return p}
describe('editing safeguards across entry points',()=>{
 beforeEach(()=>{vi.stubEnv("NEXT_PUBLIC_SUPABASE_URL","");vi.stubEnv("NEXT_PUBLIC_SUPABASE_ANON_KEY","");setup()});
 afterEach(()=>vi.unstubAllEnvs());
 it('rejects a group move when a companion would leave the room',()=>{const p=useStudio.getState().projects[0];useStudio.getState().moveItem(p.items[0].id,{x:200});expect(useStudio.getState().projects[0].items.map(i=>i.x)).toEqual([0,1500]);expect(useStudio.getState().editError).toContain('rejected')});
 it('rejects a group move when a companion is locked',()=>{const p=setup();p.items[1].locked=true;useStudio.setState({projects:[p]});useStudio.getState().moveItem(p.items[0].id,{z:100});expect(useStudio.getState().projects[0].items[0].z).toBe(0);expect(useStudio.getState().editError).toContain('locked')});
 it('blocks fields and batch tools from moving locked objects but permits finishes',()=>{const p=setup();p.items[0].locked=true;useStudio.setState({projects:[p]});const s=useStudio.getState();s.updateItem(p.items[0].id,{x:50});s.updateItems([p.items[0].id],{width:500});expect(useStudio.getState().projects[0].items[0]).toMatchObject({x:0,width:400});s.updateItem(p.items[0].id,{worktopEdge:'rounded'});expect(useStudio.getState().projects[0].items[0].worktopEdge).toBe('rounded')});
 it('validates batch positions together and rejects all when one clashes',()=>{const p=setup();useStudio.getState().updateItems(p.items.map(i=>i.id),{x:200});expect(useStudio.getState().projects[0].items.map(i=>i.x)).toEqual([0,1500]);expect(useStudio.getState().past).toHaveLength(0)});
 it('keeps a full-room paste atomic and reports no space',()=>{const p=setup();p.roomWidth=400;p.roomDepth=400;p.items=p.items.slice(0,1);useStudio.setState({projects:[p]});useStudio.getState().copyItems([p.items[0].id]);useStudio.getState().pasteItems();expect(useStudio.getState().projects[0].items).toHaveLength(1);expect(useStudio.getState().editError).toContain('no valid space')});
 it('undoes and redoes a successful group movement',()=>{const p=setup();useStudio.getState().checkpoint();useStudio.getState().moveItem(p.items[0].id,{z:100});expect(useStudio.getState().projects[0].items.every(i=>i.z===100)).toBe(true);useStudio.getState().undo();expect(useStudio.getState().projects[0].items.every(i=>i.z===0)).toBe(true);useStudio.getState().redo();expect(useStudio.getState().projects[0].items.every(i=>i.z===100)).toBe(true)});
 it('enforces the rear service gap in each orientation',()=>{const p=setup();p.items=[];for(const rotation of [0,90,180,270]){const i={...newItem('Washing machine'),width:400,depth:400,x:50,z:50,rotation};if(rotation===180)i.z=1550;if(rotation===270)i.x=1550;expect(canPlace(p,i)).toBe(true);if(rotation===0)i.z=0;if(rotation===90)i.x=0;if(rotation===180)i.z=1600;if(rotation===270)i.x=1600;expect(canPlace(p,i)).toBe(false);p.items=[i];expect(validate(p).some(v=>v.includes('service clearance'))).toBe(true);p.items=[]}});
 it('allows more than two local testing projects without reusing cloud versions on a copy',()=>{const p=setup();p.cloudVersion=3;useStudio.setState({projects:[p]});useStudio.getState().duplicateProject();expect(useStudio.getState().projects[1].cloudVersion).toBeUndefined();useStudio.getState().addProject();expect(useStudio.getState().projects).toHaveLength(3);useStudio.getState().duplicateProject();expect(useStudio.getState().projects).toHaveLength(4);expect(useStudio.getState().editError).toBe('')});
 it('retains the Basic allowance for configured cloud accounts',()=>{vi.stubEnv('NEXT_PUBLIC_SUPABASE_URL','https://example.supabase.co');vi.stubEnv('NEXT_PUBLIC_SUPABASE_ANON_KEY','test-key');useStudio.getState().addProject();useStudio.getState().addProject();expect(useStudio.getState().projects).toHaveLength(2);expect(useStudio.getState().editError).toContain('two projects');useStudio.getState().duplicateProject();expect(useStudio.getState().projects).toHaveLength(2)});
});
