import {PGlite} from '@electric-sql/pglite';
import {it} from 'vitest';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
it('executes the snapshot migration, optimistic versions, rollback and account RLS in PostgreSQL',async()=>{
const db=new PGlite();
await db.exec(`create schema auth;create table auth.users(id uuid primary key);create role authenticated;create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;grant usage on schema auth to authenticated;grant execute on function auth.uid() to authenticated;`);
const schema=(await fs.readFile('supabase/schema.sql','utf8')).replace('create extension if not exists pgcrypto;','');
await db.exec(schema);await db.exec(schema);
await db.exec(`grant usage on schema public to authenticated;grant select,insert,update,delete on all tables in schema public to authenticated;insert into auth.users values('11111111-1111-4111-8111-111111111111'),('22222222-2222-4222-8222-222222222222');set role authenticated;set request.jwt.claim.sub='11111111-1111-4111-8111-111111111111';`);
let checks=0;
const design={id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',name:'Kitchen',reference:'QA01',status:'Draft',revision:1,roomWidth:4200,roomHeight:2400,roomDepth:3400,items:[{worktopEdge:'Rounded',custom:'retained'}],revisions:[{snapshot:{items:[]}}]};
const save=async(d:Record<string,unknown>,v:number)=>(await db.query<{version:number}>('select public.save_design($1::jsonb,$2::bigint) as version',[JSON.stringify(d),v])).rows[0].version;
const fail=async(fn:()=>Promise<unknown>,pattern:RegExp)=>{await assert.rejects(fn,pattern);checks++};
assert.equal(Number(await save(design,0)),1);checks++;
assert.deepEqual((await db.query<{design_snapshot:unknown}>('select design_snapshot from public.projects')).rows[0].design_snapshot,design);checks++;
assert.equal(Number(await save({...design,name:'Updated'},1)),2);checks++;
await fail(()=>save({...design,name:'Stale'},1),/Save conflict/);
await fail(()=>save({...design,roomWidth:null},2),/not-null|null value/);
assert.equal((await db.query<{name:string;save_version:number}>('select name,save_version from public.projects')).rows[0].name,'Updated');checks++;
await db.exec(`set request.jwt.claim.sub='22222222-2222-4222-8222-222222222222'`);
assert.equal((await db.query('select * from public.projects')).rows.length,0);checks++;
await fail(()=>save(design,0),/duplicate key|row-level security|Access denied/);
await db.exec(`set request.jwt.claim.sub='11111111-1111-4111-8111-111111111111'`);
await save({...design,id:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'},0);
await fail(()=>save({...design,id:'cccccccc-cccc-4ccc-8ccc-cccccccccccc'},0),/two projects/);
await fail(()=>db.query(`insert into public.projects(user_id,name,reference,room_width,room_height,room_depth) values(auth.uid(),'Bypass','X',1000,2000,1000)`),/two projects/);
await db.query('delete from public.projects where id=$1',[design.id]);
await fail(()=>save(design,2),/project deleted/);
assert.equal(checks,11);
await db.close();
},30000);
