'use client';
import {useState} from 'react';
import Link from 'next/link';
const shared=['Measured 2D plans & elevations','3D previews & material finishes','Revisions, JSON backups & PDF packs'];
const comparison=[['Projects','Up to 2','Expanded allowance planned','Agreed with your team'],['Design tools','Current studio tools','Current tools at launch','Scope agreed with sales'],['Cloud storage','Requires a configured account','Planned with subscription','Rollout requirements reviewed'],['Billing','Free','£21 monthly / £249 annually','Contact sales'],['Availability','Local testing open','Register interest','Discuss your requirements']];
export default function Pricing(){const [annual,setAnnual]=useState(true);return <>
<div className="pricingControls"><div className="billingToggle" role="group" aria-label="Billing period"><button aria-pressed={!annual} onClick={()=>setAnnual(false)}>Monthly</button><button aria-pressed={annual} onClick={()=>setAnnual(true)}>Annually <span>£249 / year</span></button></div><p>One editor. One clear price. All prices exclude tax.</p></div>
<div className="pricingGrid">
<article className="priceCard"><div className="planHeading"><span className="planSymbol">01</span><span className="availability">TEST THE STUDIO</span></div><h2>Basic</h2><p className="planDescription">A space to explore your first ideas.</p><div className="price">£0<span>/ month</span></div><p className="priceSub">Up to two projects. No payment required.</p><Link className="siteButton outline" href="/studio">Open the studio <span aria-hidden="true">↗</span></Link><div className="planIncludes">YOUR STARTING POINT</div><ul><li>Up to two projects</li>{shared.map(x=><li key={x}>{x}</li>)}<li>Browser saving for team testing</li></ul><p className="planFootnote">Cloud saving requires a configured account.</p></article>
<article className="priceCard featured"><div className="planHeading"><span className="planSymbol">02</span><span className="availability">PLANNED SUBSCRIPTION</span></div><h2>Pro</h2><p className="planDescription">More room for your next chapter.</p><div className="price" aria-live="polite">{annual?'£249':'£21'}<span>/ {annual?'year':'month'}</span></div><p className="priceSub">Per editor · {annual?'£20.75 per month, billed annually':'Billed monthly'}.</p><Link className="siteButton" href="/signup">Register interest <span aria-hidden="true">↗</span></Link><div className="planIncludes">AT SUBSCRIPTION LAUNCH</div><ul><li>14-day free trial planned</li><li>Expanded project allowance planned</li>{shared.map(x=><li key={x}>{x}</li>)}</ul><p className="planFootnote">Subscriptions and trial activation are not live yet.</p></article>
<article className="priceCard enterpriseCard"><div className="planHeading"><span className="planSymbol">03</span><span className="availability">FOR YOUR COMPANY</span></div><h2>Enterprise</h2><p className="planDescription">Built around the way your team works.</p><div className="price enterprisePrice">Let’s talk<span> A plan shaped together</span></div><p className="priceSub">Requirements, rollout and pricing agreed with sales.</p><Link className="siteButton light" href="/enterprise#enquiry">Contact sales <span aria-hidden="true">↗</span></Link><div className="planIncludes">START THE CONVERSATION</div><ul><li>Company rollout requirements</li><li>Onboarding discussion</li><li>White-label development scope</li><li>Account and workflow requirements</li><li>Pricing agreed with sales</li></ul><p className="planFootnote">Company branding and tenancy require development.</p></article>
</div>
<div className="pricingLaunchNote"><span className="launchDot"/><p><strong>Try what’s here today.</strong> Local team testing is open. Paid plans are proposed launch prices; checkout and trials are not active.</p><Link href="/product">Explore the product <span aria-hidden="true">→</span></Link></div>
<section className="planComparison" aria-labelledby="compare-heading"><div className="pricingSectionHeading"><div><p className="eyebrow">THE DETAILS, SIDE BY SIDE</p><h2 id="compare-heading">Find your fit.</h2></div><p>A clear view of what is available today<br/>and what comes with the next stage.</p></div><div className="comparisonScroll" tabIndex={0} role="region" aria-label="Plan comparison"><table><caption className="srOnly">Basic, Pro and Enterprise plan comparison</caption><thead><tr><th scope="col">Your workspace</th><th scope="col">Basic</th><th scope="col">Pro <small>Planned</small></th><th scope="col">Enterprise</th></tr></thead><tbody>{comparison.map(row=><tr key={row[0]}><th scope="row">{row[0]}</th>{row.slice(1).map((cell,i)=><td key={i}>{cell}</td>)}</tr>)}</tbody></table></div></section>
<section className="pricingFaq" aria-labelledby="faq-heading"><div><p className="eyebrow">A FEW GOOD QUESTIONS</p><h2 id="faq-heading">Before you begin.</h2><p>Something else on your mind?</p><Link className="textLink" href="/resources/help">Visit the help centre →</Link></div><div>{[['Can I try Joinery Studio now?','Yes. Open the studio without a login for local team testing. Designs save in the browser you use; export a JSON backup to keep or move your work.'],['How does annual pricing work?','The proposed annual Pro plan is £249 per editor, excluding tax. That works out at £20.75 per month. The proposed monthly plan is £21 per editor. Paid checkout is not active yet.'],['Is the 14-day trial available?','The trial is planned for the paid-plan launch. You can test the current local studio now without payment.'],['Which file formats are supported?','Import and export Joinery Studio JSON backups, and export PDF drawing packs. CAD import, OCR, AR/VR and live collaboration are future development.'],['Can you brand it for our showroom?','Contact sales to discuss white-label requirements. Company branding, tenancy and rollout are development scope, rather than existing self-service features.']].map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></section>
<div className="pricingClosing"><div><p className="eyebrow">FROM YOUR FIRST IDEA</p><h2>Make room for possibility.</h2><p>Start with a kitchen, a bedroom or a stair concept.</p></div><Link className="siteButton" href="/studio">Start a design ↗</Link></div>
</>}
