'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {navigation} from '@/lib/siteContent';
export default function SiteNavigation(){const path=usePathname(),[open,setOpen]=useState<string|null>(null),[mobile,setMobile]=useState(false),root=useRef<HTMLElement>(null);
useEffect(()=>{setOpen(null);setMobile(false)},[path]);
useEffect(()=>{const outside=(e:PointerEvent)=>{if(root.current&&!root.current.contains(e.target as Node)){setOpen(null);setMobile(false)}};const escape=(e:KeyboardEvent)=>{if(e.key==='Escape'){const button=root.current?.querySelector<HTMLButtonElement>(`button[aria-expanded="true"]`);setOpen(null);setMobile(false);button?.focus()}};document.addEventListener('pointerdown',outside);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',escape)}},[]);
return <header className="siteHeader refinedHeader" ref={root}><Link href="/" className="siteLogo" aria-label="Joinery Studio home"><span className="logoMark">J</span>joinery<span>studio</span></Link><button className="mobileNavToggle" aria-expanded={mobile} aria-controls="site-navigation" onClick={()=>{setMobile(!mobile);setOpen(null)}}>{mobile?'Close':'Menu'}<span aria-hidden="true">{mobile?'×':'☰'}</span></button><div className={'navigationWrap '+(mobile?'mobileOpen':'')} id="site-navigation"><nav aria-label="Main navigation">{navigation.map((group,i)=>{const active=group.links.some(([,p])=>path==='/'+p);return <div className="navGroup" key={group.label}><button className={'navTrigger '+(active?'active':'')} aria-expanded={open===group.label} aria-controls={'nav-panel-'+i} onClick={()=>setOpen(open===group.label?null:group.label)}>{group.label}<svg width="12" height="12" viewBox="0 0 12 12" aria-hidden="true"><path d="m3 4.5 3 3 3-3" fill="none" stroke="currentColor" strokeWidth="1.5"/></svg></button>{open===group.label&&<div className="navPanel" id={'nav-panel-'+i}><p>{group.label}</p>{group.links.map(([label,p])=><Link key={p} href={'/'+p} aria-current={path==='/'+p?'page':undefined} onClick={()=>{setOpen(null);setMobile(false)}}>{label}<span aria-hidden="true">↗</span></Link>)}</div>}</div>})}<Link className={'navPricing '+(path==='/pricing'?'active':'')} aria-current={path==='/pricing'?'page':undefined} href="/pricing" onClick={()=>setMobile(false)}>Pricing</Link></nav><div className="navActions"><Link href="/login">Log in</Link><Link className="siteButton small" href="/studio">Open studio <span aria-hidden="true">↗</span></Link></div></div></header>}
