import {supabase,hasSupabase} from "./supabase";import {Project} from "@/types/model";
export async function signIn(email:string,password:string){return supabase().auth.signInWithPassword({email,password})}
export async function signUp(email:string,password:string){return supabase().auth.signUp({email,password})}
export async function signOut(){return supabase().auth.signOut()}
export async function currentUser(){if(!hasSupabase())return null;return (await supabase().auth.getUser()).data.user}
export function onAuthChange(cb:(email:string|null)=>void){const {data}=supabase().auth.onAuthStateChange((_event,session)=>cb(session?.user?.email??null));return()=>data.subscription.unsubscribe()}
export async function loadCloud():Promise<Project[]>{const db=supabase();const {data:ps,error}=await db.from("projects").select("*").order("updated_at",{ascending:false});if(error)throw error;const out:Project[]=[];for(const p of ps??[]){const [itemsResult,revsResult]=await Promise.all([db.from("project_items").select("*").eq("project_id",p.id),db.from("project_revisions").select("*").eq("project_id",p.id).order("revision")]);if(itemsResult.error)throw itemsResult.error;if(revsResult.error)throw revsResult.error;const items=itemsResult.data??[],revs=revsResult.data??[];out.push({id:p.id,name:p.name,customer:p.customer,reference:p.reference,status:p.status,revision:p.revision,roomWidth:p.room_width,roomHeight:p.room_height,roomDepth:p.room_depth,rules:{wallClearance:p.wall_clearance,componentGap:p.component_gap,snap:p.snap},createdAt:p.created_at,updatedAt:p.updated_at,items:(items??[]).map(i=>({id:i.id,name:i.name,type:i.type,x:i.x,y:i.y,z:i.z,width:i.width,height:i.height,depth:i.depth,shelves:i.shelves,doors:i.doors,materialId:i.material_id,finish:i.finish,notes:i.notes,locked:i.locked,hardware:i.hardware,edgeBanding:i.edge_banding})),revisions:(revs??[]).map(r=>({id:r.id,revision:r.revision,createdAt:r.created_at,snapshot:r.snapshot}))})}return out}
export async function saveCloud(p:Project){const db=supabase();const u=(await db.auth.getUser()).data.user;if(!u)throw new Error("Sign in first");const row={id:p.id,user_id:u.id,name:p.name,customer:p.customer,reference:p.reference,status:p.status,revision:p.revision,room_width:p.roomWidth,room_height:p.roomHeight,room_depth:p.roomDepth,wall_clearance:p.rules.wallClearance,component_gap:p.rules.componentGap,snap:p.rules.snap,updated_at:new Date().toISOString()};let e=(await db.from("projects").upsert(row)).error;if(e)throw e;e=(await db.from("project_items").delete().eq("project_id",p.id)).error;if(e)throw e;if(p.items.length){e=(await db.from("project_items").insert(p.items.map(i=>({id:i.id,project_id:p.id,name:i.name,type:i.type,x:i.x,y:i.y,z:i.z,width:i.width,height:i.height,depth:i.depth,shelves:i.shelves,doors:i.doors,material_id:i.materialId,finish:i.finish,notes:i.notes,locked:i.locked,hardware:i.hardware,edge_banding:i.edgeBanding})))).error;if(e)throw e}for(const r of p.revisions){e=(await db.from("project_revisions").upsert({id:r.id,project_id:p.id,revision:r.revision,snapshot:r.snapshot,created_at:r.createdAt})).error;if(e)throw e}}
export async function saveAllCloud(projects:Project[]){for(const p of projects)await saveCloud(p)}
export async function deleteCloud(id:string){const {error}=await supabase().from("projects").delete().eq("id",id);if(error)throw error}