import {Material} from "@/types/model";
import {SPLASHBACK_MATERIALS} from "./splashbacks";
// Generic design finishes inspired by common UK worktop ranges, not supplier SKUs.
export const WORKTOP_MATERIALS:Material[]=[
{id:"wt-1",code:"WT01",name:"Oak solid wood",colour:"#b98e5d",thickness:40,category:"Worktop",worktopMaterial:"Solid wood",worktopStyle:"Wood",colourFamily:"Brown",surfaceFinish:"Oiled"},
{id:"wt-2",code:"WT02",name:"Walnut solid wood",colour:"#8c6546",thickness:40,category:"Worktop",worktopMaterial:"Solid wood",worktopStyle:"Wood",colourFamily:"Brown",surfaceFinish:"Oiled"},
{id:"wt-3",code:"WT03",name:"Beech solid wood",colour:"#d7bd8b",thickness:40,category:"Worktop",worktopMaterial:"Solid wood",worktopStyle:"Wood",colourFamily:"Brown",surfaceFinish:"Oiled"},
{id:"wt-4",code:"WT04",name:"Black granite effect laminate",colour:"#292a2b",thickness:38,category:"Worktop",worktopMaterial:"Laminate",worktopStyle:"Granite",colourFamily:"Black",surfaceFinish:"Semi-gloss"},
{id:"wt-5",code:"WT05",name:"White quartz effect laminate",colour:"#f0ede6",thickness:38,category:"Worktop",worktopMaterial:"Laminate",worktopStyle:"Quartz",colourFamily:"White",surfaceFinish:"Matt"},
{id:"wt-6",code:"WT06",name:"Calacatta marble effect laminate",colour:"#efebe4",thickness:38,category:"Worktop",worktopMaterial:"Laminate",worktopStyle:"Marble",colourFamily:"White",surfaceFinish:"Semi-gloss"},
{id:"wt-7",code:"WT07",name:"Grey concrete effect laminate",colour:"#999792",thickness:38,category:"Worktop",worktopMaterial:"Laminate",worktopStyle:"Concrete",colourFamily:"Grey",surfaceFinish:"Textured matt"},
{id:"wt-8",code:"WT08",name:"Light stone effect laminate",colour:"#cbbfa9",thickness:38,category:"Worktop",worktopMaterial:"Laminate",worktopStyle:"Stone",colourFamily:"Brown",surfaceFinish:"Textured matt"},
{id:"wt-9",code:"WT09",name:"Black sparkle laminate",colour:"#252529",thickness:38,category:"Worktop",worktopMaterial:"Laminate",worktopStyle:"Sparkle",colourFamily:"Black",surfaceFinish:"Gloss"},
{id:"wt-10",code:"WT10",name:"White sparkle laminate",colour:"#f1f0eb",thickness:38,category:"Worktop",worktopMaterial:"Laminate",worktopStyle:"Sparkle",colourFamily:"White",surfaceFinish:"Gloss"},
{id:"wt-11",code:"WT11",name:"Slate effect laminate",colour:"#555b60",thickness:38,category:"Worktop",worktopMaterial:"Laminate",worktopStyle:"Slate",colourFamily:"Grey",surfaceFinish:"Textured matt"},
{id:"wt-12",code:"WT12",name:"Oak effect laminate",colour:"#c7a477",thickness:38,category:"Worktop",worktopMaterial:"Laminate",worktopStyle:"Wood",colourFamily:"Brown",surfaceFinish:"Matt"},
{id:"wt-13",code:"WT13",name:"White marble effect compact laminate",colour:"#eeeae4",thickness:12,category:"Worktop",worktopMaterial:"Compact laminate",worktopStyle:"Marble",colourFamily:"White",surfaceFinish:"Matt"},
{id:"wt-14",code:"WT14",name:"Dark slate effect compact laminate",colour:"#343b40",thickness:12,category:"Worktop",worktopMaterial:"Compact laminate",worktopStyle:"Slate",colourFamily:"Black",surfaceFinish:"Textured matt"},
{id:"wt-15",code:"WT15",name:"Carrara effect solid surface",colour:"#e7e3dc",thickness:20,category:"Worktop",worktopMaterial:"Solid surface",worktopStyle:"Marble",colourFamily:"White",surfaceFinish:"Matt"},
{id:"wt-16",code:"WT16",name:"White solid surface",colour:"#f5f3ee",thickness:20,category:"Worktop",worktopMaterial:"Solid surface",worktopStyle:"Plain",colourFamily:"White",surfaceFinish:"Matt"},
{id:"wt-17",code:"WT17",name:"Beige matt bonded surface",colour:"#c5b6a1",thickness:38,category:"Worktop",worktopMaterial:"Bonded matt surface",worktopStyle:"Plain",colourFamily:"Brown",surfaceFinish:"Matt"},
{id:"wt-18",code:"WT18",name:"Black matt solid surface",colour:"#252729",thickness:12,category:"Worktop",worktopMaterial:"Solid matt surface",worktopStyle:"Plain",colourFamily:"Black",surfaceFinish:"Matt"},
{id:"wt-19",code:"WT19",name:"Forest green laminate",colour:"#405b4f",thickness:38,category:"Worktop",worktopMaterial:"Laminate",worktopStyle:"Plain",colourFamily:"Green",surfaceFinish:"Matt"},
{id:"wt-20",code:"WT20",name:"Deep blue laminate",colour:"#344a63",thickness:38,category:"Worktop",worktopMaterial:"Laminate",worktopStyle:"Plain",colourFamily:"Blue",surfaceFinish:"Matt"},
{id:"wt-21",code:"WT21",name:"Black granite",colour:"#343437",thickness:30,category:"Worktop",worktopMaterial:"Granite",worktopStyle:"Granite",colourFamily:"Black",surfaceFinish:"Gloss"},
{id:"wt-22",code:"WT22",name:"White quartz",colour:"#eeeae5",thickness:20,category:"Worktop",worktopMaterial:"Quartz",worktopStyle:"Quartz",colourFamily:"White",surfaceFinish:"Gloss"},
{id:"wt-23",code:"WT23",name:"White marble",colour:"#e9e5df",thickness:20,category:"Worktop",worktopMaterial:"Marble",worktopStyle:"Marble",colourFamily:"White",surfaceFinish:"Gloss"},
];
export const CABINET_FINISHES:Material[]=[
{id:"palette-1",code:"C01",name:"Porcelain",colour:"#f1efea",thickness:18,category:"Painted board",surfaceFinish:"Matt"},
{id:"palette-2",code:"C02",name:"Ivory",colour:"#e9e1d2",thickness:18,category:"Painted board",surfaceFinish:"Matt"},
{id:"palette-3",code:"C03",name:"Cream",colour:"#e5d7ba",thickness:18,category:"Painted board",surfaceFinish:"Matt"},
{id:"palette-4",code:"C04",name:"Sand",colour:"#cbbc9f",thickness:18,category:"Painted board",surfaceFinish:"Matt"},
{id:"palette-5",code:"C05",name:"Cashmere",colour:"#b8aaa0",thickness:18,category:"Painted board",surfaceFinish:"Matt"},
{id:"palette-6",code:"C06",name:"Taupe",colour:"#99897c",thickness:18,category:"Painted board",surfaceFinish:"Matt"},
{id:"palette-7",code:"C07",name:"Clay",colour:"#a4826d",thickness:18,category:"Painted board",surfaceFinish:"Matt"},
{id:"palette-8",code:"C08",name:"Terracotta",colour:"#a76249",thickness:18,category:"Painted board",surfaceFinish:"Matt"},
{id:"palette-9",code:"C09",name:"Mocha",colour:"#76604e",thickness:18,category:"Painted board",surfaceFinish:"Matt"},
{id:"palette-10",code:"C10",name:"Chocolate",colour:"#49372d",thickness:18,category:"Painted board",surfaceFinish:"Matt"},
{id:"palette-11",code:"C11",name:"Pebble",colour:"#b0ada4",thickness:18,category:"Painted board",surfaceFinish:"Matt"},
{id:"palette-12",code:"C12",name:"Silver grey",colour:"#a6a8a8",thickness:18,category:"Painted board",surfaceFinish:"Matt"},
{id:"palette-13",code:"C13",name:"Stone grey",colour:"#858681",thickness:18,category:"Painted board",surfaceFinish:"Matt"},
{id:"palette-14",code:"C14",name:"Slate grey",colour:"#606970",thickness:18,category:"Painted board",surfaceFinish:"Matt"},
{id:"palette-15",code:"C15",name:"Charcoal",colour:"#393b3d",thickness:18,category:"Painted board",surfaceFinish:"Matt"},
{id:"palette-16",code:"C16",name:"Soft black",colour:"#252628",thickness:18,category:"Painted board",surfaceFinish:"Matt"},
{id:"palette-17",code:"C17",name:"Sage",colour:"#9ba58c",thickness:18,category:"Painted board",surfaceFinish:"Matt"},
{id:"palette-18",code:"C18",name:"Olive",colour:"#747b57",thickness:18,category:"Painted board",surfaceFinish:"Matt"},
{id:"palette-19",code:"C19",name:"Forest",colour:"#354d40",thickness:18,category:"Painted board",surfaceFinish:"Matt"},
{id:"palette-20",code:"C20",name:"Emerald",colour:"#246257",thickness:18,category:"Painted board",surfaceFinish:"Matt"},
{id:"palette-21",code:"C21",name:"Mint",colour:"#b3c9bd",thickness:18,category:"Painted board",surfaceFinish:"Matt"},
{id:"palette-22",code:"C22",name:"Duck egg",colour:"#a2bfc0",thickness:18,category:"Painted board",surfaceFinish:"Matt"},
{id:"palette-23",code:"C23",name:"Petrol",colour:"#2d5b65",thickness:18,category:"Painted board",surfaceFinish:"Matt"},
{id:"palette-24",code:"C24",name:"Navy",colour:"#293a51",thickness:18,category:"Painted board",surfaceFinish:"Matt"},
{id:"palette-25",code:"C25",name:"Midnight blue",colour:"#202d3a",thickness:18,category:"Painted board",surfaceFinish:"Matt"},
{id:"palette-26",code:"C26",name:"Denim",colour:"#627a90",thickness:18,category:"Painted board",surfaceFinish:"Matt"},
{id:"palette-27",code:"C27",name:"Powder blue",colour:"#a2b5c7",thickness:18,category:"Painted board",surfaceFinish:"Matt"},
{id:"palette-28",code:"C28",name:"Dusty rose",colour:"#c6a09b",thickness:18,category:"Painted board",surfaceFinish:"Matt"},
{id:"palette-29",code:"C29",name:"Blush",colour:"#dec0b8",thickness:18,category:"Painted board",surfaceFinish:"Matt"},
{id:"palette-30",code:"C30",name:"Burgundy",colour:"#66393e",thickness:18,category:"Painted board",surfaceFinish:"Matt"},
{id:"palette-31",code:"C31",name:"Mustard",colour:"#bb9652",thickness:18,category:"Painted board",surfaceFinish:"Matt"},
{id:"palette-32",code:"C32",name:"Ochre",colour:"#c8ae78",thickness:18,category:"Painted board",surfaceFinish:"Matt"},
{id:"timber-1",code:"T01",name:"Light oak",colour:"#cdb58b",thickness:18,category:"Woodgrain",surfaceFinish:"Oiled"},
{id:"timber-2",code:"T02",name:"Smoked oak",colour:"#796148",thickness:18,category:"Woodgrain",surfaceFinish:"Oiled"},
{id:"timber-3",code:"T03",name:"Honey oak",colour:"#ba8c55",thickness:18,category:"Woodgrain",surfaceFinish:"Oiled"},
{id:"timber-4",code:"T04",name:"Dark walnut",colour:"#684b36",thickness:18,category:"Woodgrain",surfaceFinish:"Oiled"},
{id:"timber-5",code:"T05",name:"Natural ash",colour:"#d7c5a1",thickness:18,category:"Woodgrain",surfaceFinish:"Oiled"},
{id:"timber-6",code:"T06",name:"Maple",colour:"#dfc9a0",thickness:18,category:"Woodgrain",surfaceFinish:"Oiled"},
{id:"timber-7",code:"T07",name:"Cherry",colour:"#a66c48",thickness:18,category:"Woodgrain",surfaceFinish:"Oiled"},
{id:"timber-8",code:"T08",name:"Black stained oak",colour:"#38312b",thickness:18,category:"Woodgrain",surfaceFinish:"Oiled"},
];
export const MATERIALS:Material[]=[
{id:"u961",code:"U961",name:"Graphite Grey",colour:"#4a4b4d",thickness:18,category:"Decorative board"},
{id:"u705",code:"U705",name:"Angora Grey",colour:"#b9b1a6",thickness:18,category:"Decorative board"},
{id:"w1000",code:"W1000",name:"Premium White",colour:"#f4f3ef",thickness:18,category:"Decorative board"},
{id:"painted-mdf",code:"PMDF",name:"Warm White Painted MDF",colour:"#eee9e1",thickness:18,category:"Painted board"},
{id:"h1180",code:"H1180",name:"Natural Halifax Oak",colour:"#b98e5d",thickness:18,category:"Woodgrain"},
{id:"h1385",code:"H1385",name:"Natural Casella Oak",colour:"#c7a477",thickness:18,category:"Woodgrain"},
{id:"u399",code:"U399",name:"Garnet Red",colour:"#7e1f28",thickness:18,category:"Decorative board"},
{id:"mdf",code:"MDF",name:"Raw MDF",colour:"#c5aa82",thickness:18,category:"Board"},
{id:"birch",code:"PLY",name:"Birch Plywood",colour:"#d7bd8b",thickness:18,category:"Board"},
{id:"stone-light",code:"QS01",name:"Carrara Quartz",colour:"#e7e3dc",thickness:20,category:"Worktop"},
{id:"stone-dark",code:"QS02",name:"Graphite Quartz",colour:"#46433f",thickness:20,category:"Worktop"},
{id:"glass-clear",code:"GLS",name:"Clear Glass",colour:"#b7d2db",thickness:10,category:"Glass"},
{id:"metal-brushed",code:"MET",name:"Brushed Steel",colour:"#9ca1a3",thickness:2,category:"Metal"},
{id:"floor-oak",code:"FL01",name:"Natural Oak Floor",colour:"#c7ad8b",thickness:14,category:"Floor"},
{id:"floor-walnut",code:"FL02",name:"Walnut Floor",colour:"#8c6546",thickness:14,category:"Floor"},
{id:"floor-stone",code:"FL03",name:"Light Stone Tile",colour:"#d8d4cc",thickness:10,category:"Floor"},...WORKTOP_MATERIALS,...CABINET_FINISHES,...SPLASHBACK_MATERIALS];
export const material=(id:string,custom:Material[]=[])=>([...custom,...MATERIALS].find(m=>m.id===id)??MATERIALS[0]);
export const floorMaterials=(custom:Material[]=[])=>([...custom,...MATERIALS].filter(m=>m.category==="Floor"||!!m.textureDataUrl));
