import {jsPDF} from 'jspdf';
import {Project,JoineryItem,WallSide} from '@/types/model';
import {material} from './materials';
import {itemRect,viewSize,normalizeRotation,wallItemRect,wallViewSize,isItemOnWall} from './geometry';
const visible=(p:Project)=>p.items.filter(i=>i.visible!==false);
function header(doc:jsPDF,p:Project,title:string){doc.setTextColor(35,53,47);doc.setFont('helvetica','bold');doc.setFontSize(15);doc.text(title,15,16);doc.setFont('helvetica','normal');doc.setFontSize(8);doc.text(doc.splitTextToSize(`${p.name} | ${p.reference} | Revision ${p.revision}`,380).slice(0,2),15,23)}
function object(doc:jsPDF,p:Project,i:JoineryItem,r:{left:number;top:number;width:number;height:number},x:number,y:number,sc:number){const m=material(i.type==='Worktop'?(i.worktopMaterialId??i.materialId):(i.doorMaterialId??i.materialId),p.customMaterials??[]),hex=m.colour.slice(1),rgb=[0,2,4].map(k=>parseInt(hex.slice(k,k+2),16));doc.setDrawColor(60);doc.setFillColor(rgb[0],rgb[1],rgb[2]);doc.rect(x+r.left*sc,y+r.top*sc,r.width*sc,r.height*sc,'FD');
// Compact reference numbers link to the full, wrapped schedule. Small components
// deliberately have no internal label, avoiding text outside their geometry.
if(r.width*sc>=8&&r.height*sc>=6){const n=visible(p).findIndex(q=>q.id===i.id)+1,cx=x+(r.left+r.width/2)*sc,cy=y+(r.top+r.height/2)*sc;doc.setFillColor(255,255,255);doc.rect(cx-3,cy-2.5,6,5,'F');doc.setTextColor(25);doc.setFontSize(6);doc.text(String(n),cx,cy+1,{align:'center'})}}
export function exportPdf(p:Project,download=true){const doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a3'});header(doc,p,'JOINERY CONCEPT DRAWING PACK');
const views:[('front'|'top'|'side'),number,number,number,number,string][]=[['front',22,42,177,95,'FRONT ELEVATION'],['top',222,42,177,95,'PLAN'],['side',22,169,177,95,'SIDE ELEVATION']];
for(const [v,x,y,w,h,title] of views){const sz=viewSize(p,v),sc=Math.min(w/sz.w,h/sz.h);doc.setFontSize(8);doc.setTextColor(25);doc.setFont('helvetica','bold');doc.text(`${title} / 1:${(1/sc).toFixed(1)}`,x,y-6);doc.setDrawColor(50);doc.rect(x,y,sz.w*sc,sz.h*sc);for(const i of visible(p))object(doc,p,i,itemRect(i,p,v),x,y,sc);doc.setTextColor(25);doc.setFont('helvetica','normal');doc.setFontSize(7);doc.text(`${sz.w} mm`,x+sz.w*sc/2,y+sz.h*sc+8,{align:'center'});doc.text(`${sz.h} mm`,x-6,y+sz.h*sc/2,{angle:90,align:'center'})}
doc.setTextColor(25);doc.setFontSize(9);doc.text('PROJECT DETAILS',222,176);doc.setFontSize(8);const details=[`Customer: ${p.customer||'-'}`,`Reference: ${p.reference}`,`Revision: ${p.revision} | Status: ${p.status}`,`Site: ${p.address||'-'}`,`Exported: ${new Date().toISOString().slice(0,10)}`];let dy=184;for(const detail of details){const lines=doc.splitTextToSize(detail,177);doc.text(lines,222,dy);dy+=lines.length*4+3}doc.text('Object numbers refer to the item schedule.',222,Math.max(dy+3,240));
addWallElevations(doc,p);addSchedule(doc,p);if(p.notes){doc.addPage();header(doc,p,'PROJECT NOTES');doc.setFontSize(9);const lines=doc.splitTextToSize(p.notes,380);for(let n=0;n<lines.length;n+=48){if(n){doc.addPage();header(doc,p,'PROJECT NOTES / CONTINUED')}doc.text(lines.slice(n,n+48),15,40)}}
const total=doc.getNumberOfPages();for(let n=1;n<=total;n++){doc.setPage(n);doc.setTextColor(70);doc.setFont('helvetica','normal');doc.setFontSize(7);doc.line(15,280,402,280);doc.text('Concept planning only. Dimensions in mm. Verify site measurements and technical requirements before manufacture.',15,287);doc.text(`${n} / ${total}`,402,287,{align:'right'})}if(download)doc.save(p.reference+'-rev-'+p.revision+'.pdf');return doc}
function addWallElevations(doc:jsPDF,p:Project){doc.addPage();header(doc,p,'FOUR WALL ELEVATIONS');const walls:WallSide[]=['back','right','front','left'],boxes=[[22,42],[222,42],[22,169],[222,169]];walls.forEach((wall,index)=>{const [x,y]=boxes[index],sz=wallViewSize(p,wall),sc=Math.min(177/sz.w,95/sz.h);doc.setTextColor(25);doc.setFont('helvetica','bold');doc.setFontSize(8);doc.text(`${wall.toUpperCase()} WALL / 1:${(1/sc).toFixed(1)}`,x,y-6);doc.setDrawColor(50);doc.rect(x,y,sz.w*sc,sz.h*sc);for(const i of visible(p).filter(i=>isItemOnWall(p,i,wall)))object(doc,p,i,wallItemRect(i,p,wall),x,y,sc);doc.setTextColor(25);doc.setFont('helvetica','normal');doc.setFontSize(7);doc.text(`${sz.w} mm`,x+sz.w*sc/2,y+sz.h*sc+8,{align:'center'})})}
function addSchedule(doc:jsPDF,p:Project){const cols=[15,27,95,140,171,202,233,268,305,402],heads=['#','Item','Type','W / H / D','X / Y / Z','Rotation','Finish','Layer','Materials'];let y=0;const newPage=()=>{doc.addPage();header(doc,p,'ITEM / MATERIAL SCHEDULE');doc.setFillColor(236,240,231);doc.rect(15,33,387,10,'F');doc.setFont('helvetica','bold');doc.setFontSize(7);heads.forEach((t,k)=>doc.text(t,cols[k]+2,39));doc.setFont('helvetica','normal');y=43};newPage();visible(p).forEach((i,n)=>{const mat=(id?:string)=>material(id??i.materialId,p.customMaterials??[]).code;const summary=i.type.includes('staircase')?`Treads: ${mat(i.treadMaterialId)}; Risers: ${mat(i.riserMaterialId)}; Rail: ${mat(i.railingMaterialId)}`:i.type==='Worktop'?`Worktop: ${mat(i.worktopMaterialId)}; Edge: ${i.worktopEdge??'square'}`:`Carcass: ${mat(i.carcassMaterialId)}; Fronts: ${mat(i.doorMaterialId)}; Left: ${mat(i.leftSideMaterialId??i.sideMaterialId)}; Right: ${mat(i.rightSideMaterialId??i.sideMaterialId)}; Plinth: ${mat(i.plinthMaterialId)}`;const values=[String(n+1),i.name,i.type,`${i.width} / ${i.height} / ${i.depth}`,`${i.x} / ${i.y} / ${i.z}`,`${normalizeRotation(i.rotation)} deg`,i.finish||'-',i.layer??'Joinery',summary];doc.setFontSize(7);const lines=values.map((v,k)=>doc.splitTextToSize(v,cols[k+1]-cols[k]-4) as string[]),height=Math.max(12,...lines.map(a=>a.length*3.5+5));if(y+height>272)newPage();doc.setFontSize(7);doc.setTextColor(25);lines.forEach((v,k)=>doc.text(v,cols[k]+2,y+5));doc.setDrawColor(210);doc.line(15,y+height,402,y+height);y+=height})}
