import {Material} from "@/types/model";
// Supplier catalogue checked 3 October 2026. Colours are design-preview approximations.
export const SPLASHBACK_MATERIALS:Material[]=[
  {
    "id": "sb-19",
    "code": "SB19",
    "name": "Ice White Self-Adhesive Glass Splashback",
    "colour": "#efeeeb",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Plain",
    "supplier": "Splashback.co.uk",
    "supplierUrl": "https://www.splashback.co.uk/shop/splashback/ice-white-selfadhesive-glass-splashback/19.htm",
    "previewImage": "/materials/splashbacks/19.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-22",
    "code": "SB22",
    "name": "Slate Grey Self-Adhesive Glass Splashback",
    "colour": "#62696d",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Plain",
    "supplier": "Splashback.co.uk",
    "supplierUrl": "https://www.splashback.co.uk/shop/splashback/slate-grey-selfadhesive-glass-splashback/22.htm",
    "previewImage": "/materials/splashbacks/22.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-10",
    "code": "SB10",
    "name": "Black Gloss Self-Adhesive Glass Splashback",
    "colour": "#222528",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Plain",
    "supplier": "Splashback.co.uk",
    "supplierUrl": "https://www.splashback.co.uk/shop/splashback/black-gloss-selfadhesive-glass-splashback/10.htm",
    "previewImage": "/materials/splashbacks/10.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-145",
    "code": "SB145",
    "name": "Sage Green Self-Adhesive Glass Splashback",
    "colour": "#a5afa0",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Plain",
    "supplier": "Splashback.co.uk",
    "supplierUrl": "https://www.splashback.co.uk/shop/splashback/sage-green-selfadhesive-glass-splashback/145.htm",
    "previewImage": "/materials/splashbacks/145.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-144",
    "code": "SB144",
    "name": "Pale Beige Self-Adhesive Glass Splashback",
    "colour": "#d6c9b8",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Plain",
    "supplier": "Splashback.co.uk",
    "supplierUrl": "https://www.splashback.co.uk/shop/splashback/pale-beige-selfadhesive-glass-splashback/144.htm",
    "previewImage": "/materials/splashbacks/144.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-18",
    "code": "SB18",
    "name": "Cotton Cream Self-Adhesive Glass Splashback",
    "colour": "#e9e0cc",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Plain",
    "supplier": "Splashback.co.uk",
    "supplierUrl": "https://www.splashback.co.uk/shop/splashback/cotton-cream-selfadhesive-glass-splashback/18.htm",
    "previewImage": "/materials/splashbacks/18.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-7",
    "code": "SB7",
    "name": "White Mist Self-Adhesive Glass Splashback",
    "colour": "#e4e6e2",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Plain",
    "supplier": "Splashback.co.uk",
    "supplierUrl": "https://www.splashback.co.uk/shop/splashback/white-mist-selfadhesive-glass-splashback/7.htm",
    "previewImage": "/materials/splashbacks/7.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-158",
    "code": "SB158",
    "name": "Flax Yellow Self-Adhesive Glass Splashback",
    "colour": "#ded3a5",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Plain",
    "supplier": "Splashback.co.uk",
    "supplierUrl": "https://www.splashback.co.uk/shop/splashback/flax-yellow-selfadhesive-glass-splashback/158.htm",
    "previewImage": "/materials/splashbacks/158.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-157",
    "code": "SB157",
    "name": "Cool Blue Self-Adhesive Glass Splashback",
    "colour": "#a5c1cd",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Plain",
    "supplier": "Splashback.co.uk",
    "supplierUrl": "https://www.splashback.co.uk/shop/splashback/cool-blue-selfadhesive-glass-splashback/157.htm",
    "previewImage": "/materials/splashbacks/157.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-6",
    "code": "SB6",
    "name": "Midnight Blue Self-Adhesive Glass Splashback",
    "colour": "#253a56",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Plain",
    "supplier": "Splashback.co.uk",
    "supplierUrl": "https://www.splashback.co.uk/shop/splashback/midnight-blue-selfadhesive-glass-splashback/6.htm",
    "previewImage": "/materials/splashbacks/6.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-159",
    "code": "SB159",
    "name": "Soft Mink Self-Adhesive Glass Splashback",
    "colour": "#b0a399",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Metallic",
    "supplier": "Splashback.co.uk",
    "supplierUrl": "https://www.splashback.co.uk/shop/splashback/soft-mink-selfadhesive-glass-splashback/159.htm",
    "previewImage": "/materials/splashbacks/159.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-143",
    "code": "SB143",
    "name": "Bluebell Shimmer Self-Adhesive Glass Splashback",
    "colour": "#818cad",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Metallic",
    "supplier": "Splashback.co.uk",
    "supplierUrl": "https://www.splashback.co.uk/shop/splashback/bluebell-shimmer-selfadhesive-glass-splashback/143.htm",
    "previewImage": "/materials/splashbacks/143.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-20",
    "code": "SB20",
    "name": "Platinum Self-Adhesive Glass Splashback",
    "colour": "#aaaeb1",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Metallic",
    "supplier": "Splashback.co.uk",
    "supplierUrl": "https://www.splashback.co.uk/shop/splashback/platinum-selfadhesive-glass-splashback/20.htm",
    "previewImage": "/materials/splashbacks/20.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-17",
    "code": "SB17",
    "name": "Copper Self-Adhesive Glass Splashback",
    "colour": "#b97854",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Metallic",
    "supplier": "Splashback.co.uk",
    "supplierUrl": "https://www.splashback.co.uk/shop/splashback/copper-selfadhesive-glass-splashback/17.htm",
    "previewImage": "/materials/splashbacks/17.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-106",
    "code": "SB106",
    "name": "Brass Self-Adhesive Glass Splashback",
    "colour": "#b8a271",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Metallic",
    "supplier": "Splashback.co.uk",
    "supplierUrl": "https://www.splashback.co.uk/shop/splashback/brass-selfadhesive-glass-splashback/106.htm",
    "previewImage": "/materials/splashbacks/106.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-21",
    "code": "SB21",
    "name": "Rose Gold Self-Adhesive Glass Splashback",
    "colour": "#c59183",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Metallic",
    "supplier": "Splashback.co.uk",
    "supplierUrl": "https://www.splashback.co.uk/shop/splashback/rose-gold-selfadhesive-glass-splashback/21.htm",
    "previewImage": "/materials/splashbacks/21.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-161",
    "code": "SB161",
    "name": "Metallic Granite Self-Adhesive Glass Splashback",
    "colour": "#62666a",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Metallic",
    "supplier": "Splashback.co.uk",
    "supplierUrl": "https://www.splashback.co.uk/shop/splashback/metallic-granite-selfadhesive-glass-splashback/161.htm",
    "previewImage": "/materials/splashbacks/161.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-160",
    "code": "SB160",
    "name": "Ice White Sparkle Self-Adhesive Glass Splashback",
    "colour": "#efeeeb",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Sparkle",
    "supplier": "Splashback.co.uk",
    "supplierUrl": "https://www.splashback.co.uk/shop/splashback/ice-white-sparkle-selfadhesive-glass-splashback/160.htm",
    "previewImage": "/materials/splashbacks/160.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Sparkle"
  },
  {
    "id": "sb-9",
    "code": "SB9",
    "name": "Black Sparkle Self-Adhesive Glass Splashback",
    "colour": "#222528",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Sparkle",
    "supplier": "Splashback.co.uk",
    "supplierUrl": "https://www.splashback.co.uk/shop/splashback/black-sparkle-selfadhesive-glass-splashback/9.htm",
    "previewImage": "/materials/splashbacks/9.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Sparkle"
  },
  {
    "id": "sb-103",
    "code": "SB103",
    "name": "Matt Black Finish Self-Adhesive Glass Splashback",
    "colour": "#222528",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Matt",
    "splashbackFinish": "Matt",
    "supplier": "Splashback.co.uk",
    "supplierUrl": "https://www.splashback.co.uk/shop/splashback/matt-black-finish-selfadhesive-glass-splashback/103.htm",
    "previewImage": "/materials/splashbacks/103.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-105",
    "code": "SB105",
    "name": "Matt White Finish Self-Adhesive Glass Splashback",
    "colour": "#eeeae3",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Matt",
    "splashbackFinish": "Matt",
    "supplier": "Splashback.co.uk",
    "supplierUrl": "https://www.splashback.co.uk/shop/splashback/matt-white-finish-selfadhesive-glass-splashback/105.htm",
    "previewImage": "/materials/splashbacks/105.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-104",
    "code": "SB104",
    "name": "Matt Grey Finish Self-Adhesive Glass Splashback",
    "colour": "#b8b4aa",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Matt",
    "splashbackFinish": "Matt",
    "supplier": "Splashback.co.uk",
    "supplierUrl": "https://www.splashback.co.uk/shop/splashback/matt-grey-finish-selfadhesive-glass-splashback/104.htm",
    "previewImage": "/materials/splashbacks/104.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-15",
    "code": "SB15",
    "name": "Carrara Marble Self-Adhesive Glass Splashback",
    "colour": "#e9e7e1",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Marble",
    "supplier": "Splashback.co.uk",
    "supplierUrl": "https://www.splashback.co.uk/shop/splashback/carrara-marble-selfadhesive-glass-splashback/15.htm",
    "previewImage": "/materials/splashbacks/15.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Marble"
  },
  {
    "id": "sb-4",
    "code": "SB4",
    "name": "Calacatta Marble Self-Adhesive Glass Splashback",
    "colour": "#e9e7e1",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Marble",
    "supplier": "Splashback.co.uk",
    "supplierUrl": "https://www.splashback.co.uk/shop/splashback/calacatta-marble-selfadhesive-glass-splashback/4.htm",
    "previewImage": "/materials/splashbacks/4.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Marble"
  },
  {
    "id": "sb-166",
    "code": "SB166",
    "name": "Honey Calacatta Marble Self-Adhesive Glass Splashback",
    "colour": "#dfd0b4",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Marble",
    "supplier": "Splashback.co.uk",
    "supplierUrl": "https://www.splashback.co.uk/shop/splashback/honey-calacatta-marble-selfadhesive-glass-splashback/166.htm",
    "previewImage": "/materials/splashbacks/166.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Marble"
  },
  {
    "id": "sb-1",
    "code": "SB1",
    "name": "Pietra Grey Marble Self-Adhesive Glass Splashback",
    "colour": "#55565a",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Marble",
    "supplier": "Splashback.co.uk",
    "supplierUrl": "https://www.splashback.co.uk/shop/splashback/pietra-grey-marble-selfadhesive-glass-splashback/1.htm",
    "previewImage": "/materials/splashbacks/1.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Marble"
  },
  {
    "id": "sb-162",
    "code": "SB162",
    "name": "Black Marble Self-Adhesive Glass Splashback",
    "colour": "#222528",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Marble",
    "supplier": "Splashback.co.uk",
    "supplierUrl": "https://www.splashback.co.uk/shop/splashback/black-marble-selfadhesive-glass-splashback/162.htm",
    "previewImage": "/materials/splashbacks/162.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Marble"
  },
  {
    "id": "sb-131",
    "code": "SB131",
    "name": "Clarissa Hulse Dill Silver Self-Adhesive Glass Splashback",
    "colour": "#bac0b9",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Floral",
    "supplier": "Clarissa Hulse",
    "supplierUrl": "https://www.splashback.co.uk/shop/clarissa-hulse/clarissa-hulse-dill-silver-selfadhesive-glass-splashback/131.htm",
    "previewImage": "/materials/splashbacks/131.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-132",
    "code": "SB132",
    "name": "Clarissa Hulse Meadow Grass Blue Self-Adhesive Glass Splashback",
    "colour": "#8eafb9",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Floral",
    "supplier": "Clarissa Hulse",
    "supplierUrl": "https://www.splashback.co.uk/shop/clarissa-hulse/clarissa-hulse-meadow-grass-blue-selfadhesive-glass-splashback/132.htm",
    "previewImage": "/materials/splashbacks/132.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-134",
    "code": "SB134",
    "name": "Clarissa Hulse Meadow Grass Blush Self-Adhesive Glass Splashback",
    "colour": "#d3b7b7",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Floral",
    "supplier": "Clarissa Hulse",
    "supplierUrl": "https://www.splashback.co.uk/shop/clarissa-hulse/clarissa-hulse-meadow-grass-blush-selfadhesive-glass-splashback/134.htm",
    "previewImage": "/materials/splashbacks/134.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-133",
    "code": "SB133",
    "name": "Clarissa Hulse Wild Chevril Chalk Self-Adhesive Glass Splashback",
    "colour": "#e5e2d9",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Floral",
    "supplier": "Clarissa Hulse",
    "supplierUrl": "https://www.splashback.co.uk/shop/clarissa-hulse/clarissa-hulse-wild-chevril-chalk-selfadhesive-glass-splashback/133.htm",
    "previewImage": "/materials/splashbacks/133.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-110",
    "code": "SB110",
    "name": "Laura Ashley Midnight Seaspray Self-Adhesive Glass Splashback",
    "colour": "#3a526a",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Plain",
    "supplier": "Laura Ashley",
    "supplierUrl": "https://www.splashback.co.uk/shop/laura-ashley/laura-ashley-midnight-seaspray-selfadhesive-glass-splashback/110.htm",
    "previewImage": "/materials/splashbacks/110.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-25",
    "code": "SB25",
    "name": "Laura Ashley Eau De Nil Self-Adhesive Glass Splashback",
    "colour": "#aab9b0",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Plain",
    "supplier": "Laura Ashley",
    "supplierUrl": "https://www.splashback.co.uk/shop/laura-ashley/laura-ashley-eau-de-nil-selfadhesive-glass-splashback/25.htm",
    "previewImage": "/materials/splashbacks/25.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-28",
    "code": "SB28",
    "name": "Laura Ashley Mineral Grey Self-Adhesive Glass Splashback",
    "colour": "#a5a8a6",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Plain",
    "supplier": "Laura Ashley",
    "supplierUrl": "https://www.splashback.co.uk/shop/laura-ashley/laura-ashley-mineral-grey-selfadhesive-glass-splashback/28.htm",
    "previewImage": "/materials/splashbacks/28.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-29",
    "code": "SB29",
    "name": "Laura Ashley Copper Self-Adhesive Glass Splashback",
    "colour": "#b97854",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Metallic",
    "supplier": "Laura Ashley",
    "supplierUrl": "https://www.splashback.co.uk/shop/laura-ashley/laura-ashley-copper-selfadhesive-glass-splashback/29.htm",
    "previewImage": "/materials/splashbacks/29.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-109",
    "code": "SB109",
    "name": "Laura Ashley Brass Self-Adhesive Glass Splashback",
    "colour": "#b8a271",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Metallic",
    "supplier": "Laura Ashley",
    "supplierUrl": "https://www.splashback.co.uk/shop/laura-ashley/laura-ashley-brass-selfadhesive-glass-splashback/109.htm",
    "previewImage": "/materials/splashbacks/109.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-113",
    "code": "SB113",
    "name": "Laura Ashley Metallic Fern Self-Adhesive Glass Splashback",
    "colour": "#79877a",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Metallic",
    "supplier": "Laura Ashley",
    "supplierUrl": "https://www.splashback.co.uk/shop/laura-ashley/laura-ashley-metallic-fern-selfadhesive-glass-splashback/113.htm",
    "previewImage": "/materials/splashbacks/113.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-121",
    "code": "SB121",
    "name": "Laura Ashley Oriental Garden Midnight Seaspray - Special Edition",
    "colour": "#3a526a",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Floral",
    "supplier": "Laura Ashley",
    "supplierUrl": "https://www.splashback.co.uk/shop/laura-ashley/laura-ashley-oriental-garden-midnight-seaspray--special-edition/121.htm",
    "previewImage": "/materials/splashbacks/121.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-5",
    "code": "SB5",
    "name": "Laura Ashley Mr Jones Charcoal Self-Adhesive Glass Splashback",
    "colour": "#4b4e50",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Patterned",
    "supplier": "Laura Ashley",
    "supplierUrl": "https://www.splashback.co.uk/shop/laura-ashley/laura-ashley-mr-jones-charcoal-selfadhesive-glass-splashback/5.htm",
    "previewImage": "/materials/splashbacks/5.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-30",
    "code": "SB30",
    "name": "Laura Ashley Mr Jones Dove Grey Self-Adhesive Glass Splashback",
    "colour": "#a6a8a6",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Patterned",
    "supplier": "Laura Ashley",
    "supplierUrl": "https://www.splashback.co.uk/shop/laura-ashley/laura-ashley-mr-jones-dove-grey-selfadhesive-glass-splashback/30.htm",
    "previewImage": "/materials/splashbacks/30.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-122",
    "code": "SB122",
    "name": "Laura Ashley Mr Jones Midnight Seaspray Self-Adhesive Glass Splashback",
    "colour": "#3a526a",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Patterned",
    "supplier": "Laura Ashley",
    "supplierUrl": "https://www.splashback.co.uk/shop/laura-ashley/laura-ashley-mr-jones-midnight-seaspray-selfadhesive-glass-splashback/122.htm",
    "previewImage": "/materials/splashbacks/122.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-111",
    "code": "SB111",
    "name": "Laura Ashley Wicker Midnight Seaspray Self-Adhesive Glass Splashback",
    "colour": "#3a526a",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Patterned",
    "supplier": "Laura Ashley",
    "supplierUrl": "https://www.splashback.co.uk/shop/laura-ashley/laura-ashley-wicker-midnight-seaspray-selfadhesive-glass-splashback/111.htm",
    "previewImage": "/materials/splashbacks/111.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-31",
    "code": "SB31",
    "name": "Laura Ashley Wicker Charcoal Self-Adhesive Glass Splashback",
    "colour": "#4b4e50",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Patterned",
    "supplier": "Laura Ashley",
    "supplierUrl": "https://www.splashback.co.uk/shop/laura-ashley/laura-ashley-wicker-charcoal-selfadhesive-glass-splashback/31.htm",
    "previewImage": "/materials/splashbacks/31.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-32",
    "code": "SB32",
    "name": "Laura Ashley Wicker Dove Grey Self-Adhesive Glass Splashback",
    "colour": "#a6a8a6",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Patterned",
    "supplier": "Laura Ashley",
    "supplierUrl": "https://www.splashback.co.uk/shop/laura-ashley/laura-ashley-wicker-dove-grey-selfadhesive-glass-splashback/32.htm",
    "previewImage": "/materials/splashbacks/32.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-112",
    "code": "SB112",
    "name": "Laura Ashley Lisette Metallic Charcoal Self-Adhesive Glass Splashback",
    "colour": "#4b4e50",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Metallic",
    "supplier": "Laura Ashley",
    "supplierUrl": "https://www.splashback.co.uk/shop/laura-ashley/laura-ashley-lisette-metallic-charcoal-selfadhesive-glass-splashback/112.htm",
    "previewImage": "/materials/splashbacks/112.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-27",
    "code": "SB27",
    "name": "Laura Ashley Lisette White Self-Adhesive Glass Splashback",
    "colour": "#eeeae3",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Patterned",
    "supplier": "Laura Ashley",
    "supplierUrl": "https://www.splashback.co.uk/shop/laura-ashley/laura-ashley-lisette-white-selfadhesive-glass-splashback/27.htm",
    "previewImage": "/materials/splashbacks/27.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-26",
    "code": "SB26",
    "name": "Laura Ashley Lisette Flint Self-Adhesive Glass Splashback",
    "colour": "#777e80",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Patterned",
    "supplier": "Laura Ashley",
    "supplierUrl": "https://www.splashback.co.uk/shop/laura-ashley/laura-ashley-lisette-flint-selfadhesive-glass-splashback/26.htm",
    "previewImage": "/materials/splashbacks/26.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-156",
    "code": "SB156",
    "name": "Silver Mirror Self-Adhesive Glass Splashback",
    "colour": "#bfc7cc",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Mirrored",
    "supplier": "Splashback.co.uk",
    "supplierUrl": "https://www.splashback.co.uk/shop/splashback/silver-mirror-selfadhesive-glass-splashback/156.htm",
    "previewImage": "/materials/splashbacks/156.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-155",
    "code": "SB155",
    "name": "Grey Mirror Self-Adhesive Glass Splashback",
    "colour": "#7b858b",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Mirrored",
    "supplier": "Splashback.co.uk",
    "supplierUrl": "https://www.splashback.co.uk/shop/splashback/grey-mirror-selfadhesive-glass-splashback/155.htm",
    "previewImage": "/materials/splashbacks/155.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-154",
    "code": "SB154",
    "name": "Bronze Mirror Self-Adhesive Glass Splashback",
    "colour": "#9a8470",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Mirrored",
    "supplier": "Splashback.co.uk",
    "supplierUrl": "https://www.splashback.co.uk/shop/splashback/bronze-mirror-selfadhesive-glass-splashback/154.htm",
    "previewImage": "/materials/splashbacks/154.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-34",
    "code": "SB34",
    "name": "House Beautiful Iridescent White Self-Adhesive Glass Splashback",
    "colour": "#eeeae3",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Plain",
    "supplier": "House Beautiful",
    "supplierUrl": "https://www.splashback.co.uk/shop/house-beautiful/house-beautiful-iridescent-white-selfadhesive-glass-splashback/34.htm",
    "previewImage": "/materials/splashbacks/34.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-114",
    "code": "SB114",
    "name": "Ice White Self-Adhesive Glass Bathroom Splashback",
    "colour": "#efeeeb",
    "thickness": 4,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Plain",
    "supplier": "Splashback.co.uk",
    "supplierUrl": "https://www.splashback.co.uk/shop/splashback/ice-white-selfadhesive-glass-bathroom-splashback/114.htm",
    "previewImage": "/materials/splashbacks/114.jpg",
    "splashbackRoom": "Bathroom",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-115",
    "code": "SB115",
    "name": "Pearl Shimmer Self-Adhesive Glass Bathroom Splashback",
    "colour": "#ddd9d0",
    "thickness": 4,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Metallic",
    "supplier": "Splashback.co.uk",
    "supplierUrl": "https://www.splashback.co.uk/shop/splashback/pearl-shimmer-selfadhesive-glass-bathroom-splashback/115.htm",
    "previewImage": "/materials/splashbacks/115.jpg",
    "splashbackRoom": "Bathroom",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-127",
    "code": "SB127",
    "name": "Silk Grey Self-Adhesive Glass Bathroom Splashback",
    "colour": "#bbc0bd",
    "thickness": 4,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Plain",
    "supplier": "Splashback.co.uk",
    "supplierUrl": "https://www.splashback.co.uk/shop/splashback/silk-grey-selfadhesive-glass-bathroom-splashback/127.htm",
    "previewImage": "/materials/splashbacks/127.jpg",
    "splashbackRoom": "Bathroom",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-126",
    "code": "SB126",
    "name": "Charcoal Grey Self-Adhesive Glass Bathroom Splashback",
    "colour": "#4b4e50",
    "thickness": 4,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Metallic",
    "supplier": "Splashback.co.uk",
    "supplierUrl": "https://www.splashback.co.uk/shop/splashback/charcoal-grey-selfadhesive-glass-bathroom-splashback/126.htm",
    "previewImage": "/materials/splashbacks/126.jpg",
    "splashbackRoom": "Bathroom",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-125",
    "code": "SB125",
    "name": "Matt White Finish Self-Adhesive Glass Bathroom Splashback",
    "colour": "#eeeae3",
    "thickness": 4,
    "category": "Splashback",
    "surfaceFinish": "Matt",
    "splashbackFinish": "Matt",
    "supplier": "Splashback.co.uk",
    "supplierUrl": "https://www.splashback.co.uk/shop/splashback/matt-white-finish-selfadhesive-glass-bathroom-splashback/125.htm",
    "previewImage": "/materials/splashbacks/125.jpg",
    "splashbackRoom": "Bathroom",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-124",
    "code": "SB124",
    "name": "Matt Grey Finish Self-Adhesive Glass Bathroom Splashback",
    "colour": "#b8b4aa",
    "thickness": 4,
    "category": "Splashback",
    "surfaceFinish": "Matt",
    "splashbackFinish": "Matt",
    "supplier": "Splashback.co.uk",
    "supplierUrl": "https://www.splashback.co.uk/shop/splashback/matt-grey-finish-selfadhesive-glass-bathroom-splashback/124.htm",
    "previewImage": "/materials/splashbacks/124.jpg",
    "splashbackRoom": "Bathroom",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-123",
    "code": "SB123",
    "name": "Matt Black Finish Self-Adhesive Glass Bathroom Splashback",
    "colour": "#222528",
    "thickness": 4,
    "category": "Splashback",
    "surfaceFinish": "Matt",
    "splashbackFinish": "Matt",
    "supplier": "Splashback.co.uk",
    "supplierUrl": "https://www.splashback.co.uk/shop/splashback/matt-black-finish-selfadhesive-glass-bathroom-splashback/123.htm",
    "previewImage": "/materials/splashbacks/123.jpg",
    "splashbackRoom": "Bathroom",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-128",
    "code": "SB128",
    "name": "Carrara Marble Self-Adhesive Glass Bathroom Splashback",
    "colour": "#e9e7e1",
    "thickness": 4,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Marble",
    "supplier": "Splashback.co.uk",
    "supplierUrl": "https://www.splashback.co.uk/shop/splashback/carrara-marble-selfadhesive-glass-bathroom-splashback/128.htm",
    "previewImage": "/materials/splashbacks/128.jpg",
    "splashbackRoom": "Bathroom",
    "worktopStyle": "Marble"
  },
  {
    "id": "sb-164",
    "code": "SB164",
    "name": "Calacatta Marble Self-Adhesive Glass Bathroom Splashback",
    "colour": "#e9e7e1",
    "thickness": 4,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Marble",
    "supplier": "Splashback.co.uk",
    "supplierUrl": "https://www.splashback.co.uk/shop/splashback/calacatta-marble-selfadhesive-glass-bathroom-splashback/164.htm",
    "previewImage": "/materials/splashbacks/164.jpg",
    "splashbackRoom": "Bathroom",
    "worktopStyle": "Marble"
  },
  {
    "id": "sb-167",
    "code": "SB167",
    "name": "Honey Calacatta Marble Self-Adhesive Glass Bathroom Splashback",
    "colour": "#dfd0b4",
    "thickness": 4,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Marble",
    "supplier": "Splashback.co.uk",
    "supplierUrl": "https://www.splashback.co.uk/shop/splashback/honey-calacatta-marble-selfadhesive-glass-bathroom-splashback/167.htm",
    "previewImage": "/materials/splashbacks/167.jpg",
    "splashbackRoom": "Bathroom",
    "worktopStyle": "Marble"
  },
  {
    "id": "sb-165",
    "code": "SB165",
    "name": "Pietra Grey Marble Self-Adhesive Glass Bathroom Splashback",
    "colour": "#55565a",
    "thickness": 4,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Marble",
    "supplier": "Splashback.co.uk",
    "supplierUrl": "https://www.splashback.co.uk/shop/splashback/pietra-grey-marble-selfadhesive-glass-bathroom-splashback/165.htm",
    "previewImage": "/materials/splashbacks/165.jpg",
    "splashbackRoom": "Bathroom",
    "worktopStyle": "Marble"
  },
  {
    "id": "sb-163",
    "code": "SB163",
    "name": "Black Marble Self-Adhesive Glass Bathroom Splashback",
    "colour": "#222528",
    "thickness": 4,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Marble",
    "supplier": "Splashback.co.uk",
    "supplierUrl": "https://www.splashback.co.uk/shop/splashback/black-marble-selfadhesive-glass-bathroom-splashback/163.htm",
    "previewImage": "/materials/splashbacks/163.jpg",
    "splashbackRoom": "Bathroom",
    "worktopStyle": "Marble"
  },
  {
    "id": "sb-139",
    "code": "SB139",
    "name": "Laura Ashley Wicker Pearl White Self-Adhesive Glass Bathroom Splashback",
    "colour": "#ece9e1",
    "thickness": 4,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Patterned",
    "supplier": "Laura Ashley",
    "supplierUrl": "https://www.splashback.co.uk/shop/laura-ashley/laura-ashley-wicker-pearl-white-selfadhesive-glass-bathroom-splashback/139.htm",
    "previewImage": "/materials/splashbacks/139.jpg",
    "splashbackRoom": "Bathroom",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-138",
    "code": "SB138",
    "name": "Laura Ashley Wicker Chalk Blue Self-Adhesive Glass Bathroom Splashback",
    "colour": "#adbfca",
    "thickness": 4,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Patterned",
    "supplier": "Laura Ashley",
    "supplierUrl": "https://www.splashback.co.uk/shop/laura-ashley/laura-ashley-wicker-chalk-blue-selfadhesive-glass-bathroom-splashback/138.htm",
    "previewImage": "/materials/splashbacks/138.jpg",
    "splashbackRoom": "Bathroom",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-140",
    "code": "SB140",
    "name": "Laura Ashley Mr Jones Metallic Charcoal Self-Adhesive Glass Bathroom Splashback",
    "colour": "#4b4e50",
    "thickness": 4,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Metallic",
    "supplier": "Laura Ashley",
    "supplierUrl": "https://www.splashback.co.uk/shop/laura-ashley/laura-ashley-mr-jones-metallic-charcoal-selfadhesive-glass-bathroom-splashback/140.htm",
    "previewImage": "/materials/splashbacks/140.jpg",
    "splashbackRoom": "Bathroom",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-136",
    "code": "SB136",
    "name": "Laura Ashley Onyx Blush Self-Adhesive Glass Bathroom Splashback",
    "colour": "#d3b7b7",
    "thickness": 4,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Patterned",
    "supplier": "Laura Ashley",
    "supplierUrl": "https://www.splashback.co.uk/shop/laura-ashley/laura-ashley-onyx-blush-selfadhesive-glass-bathroom-splashback/136.htm",
    "previewImage": "/materials/splashbacks/136.jpg",
    "splashbackRoom": "Bathroom",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-137",
    "code": "SB137",
    "name": "Laura Ashley Onyx Dove Grey Self-Adhesive Glass Bathroom Splashback",
    "colour": "#a6a8a6",
    "thickness": 4,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Patterned",
    "supplier": "Laura Ashley",
    "supplierUrl": "https://www.splashback.co.uk/shop/laura-ashley/laura-ashley-onyx-dove-grey-selfadhesive-glass-bathroom-splashback/137.htm",
    "previewImage": "/materials/splashbacks/137.jpg",
    "splashbackRoom": "Bathroom",
    "worktopStyle": "Plain"
  },
  {
    "id": "sb-37",
    "code": "SB37",
    "name": "House Beautiful Platino Self-Adhesive Glass Splashback",
    "colour": "#bcb9af",
    "thickness": 6,
    "category": "Splashback",
    "surfaceFinish": "Gloss",
    "splashbackFinish": "Metallic",
    "supplier": "House Beautiful",
    "supplierUrl": "https://www.splashback.co.uk/shop/house-beautiful/house-beautiful-platino-selfadhesive-glass-splashback/37.htm",
    "previewImage": "/materials/splashbacks/37.jpg",
    "splashbackRoom": "Kitchen",
    "worktopStyle": "Plain"
  }
];
