import Link from 'next/link';
import Image from 'next/image';
import {notFound} from 'next/navigation';
import {sitePages} from '@/lib/siteContent';
import MarketingShell from '@/components/MarketingShell';
import MarketingDrawing from '@/components/MarketingDrawing';
import EnquiryForm from '@/components/EnquiryForm';
export function generateStaticParams(){return Object.keys(sitePages).map(path=>({slug:path.split('/')}))}
export function generateMetadata({params}:{params:{slug:string[]}}){const page=sitePages[params.slug.join('/')];return {title:page?`${page.eyebrow} | Joinery Studio`:'Joinery Studio',description:page?.intro}}
export default function Page({params}:{params:{slug:string[]}}){const path=params.slug.join('/'),page=sitePages[path];if(!page)notFound();return <MarketingShell><main id="main-content"><section className="detailHero"><div><p className="eyebrow">{page.eyebrow}</p><h1>{page.title}</h1><p className="lead">{page.intro}</p><Link className="siteButton" href={path.startsWith('enterprise')?'#enquiry':`/studio?kind=${page.kind}`}>{path.startsWith('enterprise')?'Contact sales':page.cta??'Explore in the studio'} ↗</Link></div><MarketingDrawing kind={page.kind}/></section><section className="siteSection"><div className="actualPlan"><Image src={`/examples/${page.kind}-plan.png`} width={1600} height={760} sizes="(max-width:700px) 88vw, 80vw" alt={`Actual ${page.kind} starter plan generated from Joinery Studio objects`}/><p>Actual {page.kind} starter plan from the app. All components remain editable.</p></div><p className="eyebrow">HOW IT WORKS</p><h2>From the first idea<br/>to a clearer next step.</h2><div className="threeColumns">{page.steps.map(([title,body],i)=><article key={title}><span className="stepNumber">0{i+1}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section><section className="splitSection sageSection"><MarketingDrawing kind={page.kind} plan/><div><p className="eyebrow">THE DETAILS, IN VIEW</p>{page.features.map(([title,body])=><article className="featureLine" key={title}><h3>{title}</h3><p>{body}</p></article>)}</div></section>{path.startsWith('enterprise')&&<section className="siteSection" id="enquiry"><p className="eyebrow">LET’S TALK</p><h2>Tell us about your company.</h2><EnquiryForm intent="sales"/></section>}{path==='resources/community'&&<section className="siteSection"><a href="https://discord.com" target="_blank" rel="noreferrer" className="siteButton">Explore Discord ↗</a><p>Platform link only. The dedicated community invitation is coming later.</p></section>}<section className="closingSection"><div><p className="eyebrow">KEEP EXPLORING</p><h2>See the whole picture.</h2></div><Link href="/product" className="siteButton">Product overview ↗</Link></section></main></MarketingShell>}
